name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY2 }}
          script: |
            set -e

            echo "ğŸ” Sync code with origin/main"
            cd /home/ubuntu/finance-app
            git fetch origin
            git reset --hard origin/main

            echo "ğŸ’» Build frontend"
            cd client
            npm ci
            npm run build

            echo "ğŸš€ Deploy frontend to /var/www/html"
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            echo "ğŸ”„ Restart backend service"
            sudo systemctl restart finance.service
            sudo systemctl status finance.service --no-pager

            echo "âœ… Deployment completed successfully"
